# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'testsocketrn' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for testsocketrn
  pod 'Socket.IO-Client-Swift', '~> 12.1.2' # Or latest version
  target 'testsocketrnTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

swift4 = ['Socket.IO-Client-Swift']

post_install do |installer|
  installer.pods_project.targets.each do |target|

    swift_version = '3.2'

    if swift4.include?(target.name)
      swift_version = '4.0'
    end

    if swift_version
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = swift_version
      end
    end
  end
end
